apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-backup-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sa
roleRef:
  kind: Role
  name: etcd-backup-role
  apiGroup: rbac.authorization.k8s.io